version: '3.8'
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - HOST_SERVER
      - DB_SERVER_PORT
      - DATABASE_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SSL_MODE
      - SECRET_KEY
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
    depends_on:
      - db
    networks:
      - nginx-proxy
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - nginx-proxy

  pg_backup_s3:
    image: eeshugerman/postgres-backup-s3:13
    environment:
      S3_ENDPOINT: https://ap-south-1.linodeobjects.com     
      S3_REGION: ap-south-1
      S3_ACCESS_KEY_ID: WEPIOL2GP3OR9T25646M
      S3_SECRET_ACCESS_KEY: 8Yi7yrTdgZHSmJf7DDnczIwWLF0dTXSniID3S2ks
      S3_BUCKET: ankamala
      S3_PREFIX: backup
      POSTGRES_HOST: db
      POSTGRES_DATABASE: password
      POSTGRES_USER: password
      POSTGRES_PASSWORD: BlackJeremy1@
    networks:
      - nginx-proxy
      
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./volumes/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - nginx_html:/usr/share/nginx/html
    networks:
      - nginx-proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    environment:
      - DEBUG
      - NGINX_PROXY_CONTAINER
      - LETSENCRYPT_EMAIL

volumes:
  acme:
  certs:
  nginx_html:
  postgres_data:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy